tags:
  - name: applications
    description: applications API
  - name: chats
    description: chats API

paths:
  # [GET] applications
  /applications:
    get:
      tags:
        - applications
      summary: Find All Applications
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"

    # [POST] applications
    post:
      tags:
        - applications
      summary: Application Creation
      parameters:
        - name: body
          in: body
          description: application Data
          required: true
          schema:
            $ref: "#/definitions/applications"
      responses:
        201:
          description: "Created"
        400:
          description: "Bad Request"
        500:
          description: "Server Error"

  # [GET] applications/token
  /applications/{token}:
    get:
      tags:
        - applications
      summary: Find Application By Token
      parameters:
        - name: token
          in: path
          description: application Token
          required: true
          type: string
      responses:
        200:
          description: "OK"
        404:
          description: "Not Found"
        500:
          description: "Server Error"

    # [PUT] applications/token
    put:
      tags:
        - applications
      summary: Update Application By Token
      parameters:
        - name: token
          in: path
          description: application Token
          required: true
          type: string
        - name: body
          in: body
          description: application Data
          required: true
          schema:
            $ref: "#/definitions/applications"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
        500:
          description: "Server Error"

  # [GET] chats
  /applications/{token}/chats:
    get:
      tags:
        - chats
      summary: Find Applications Chats
      parameters:
        - name: token
          in: path
          description: application Token
          required: true
          type: string
      responses:
        200:
          description: "OK"
        500:
          description: "Server Error"
    # [POST] Chats
    post:
      tags:
        - chats
      summary: Chat Creation
      parameters:
        - name: token
          in: path
          description: application Token
          required: true
          type: string
      responses:
        201:
          description: "Created"
        400:
          description: "Bad Request"
        500:
          description: "Server Error"
    # [GET] chat
  /applications/{token}/chats/{number}:
    get:
      tags:
        - chats
      summary: Find Chat By App Token and Chat Number
      parameters:
        - name: token
          in: path
          description: application Token
          required: true
          type: string
        - name: number
          in: path
          description: chat number
          required: true
          type: string
      responses:
        200:
          description: "OK"
        404:
          description: "Not Found"
        500:
          description: "Server Error"
# definitions
definitions:
  applications:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        description: application name

schemes:
  - https
  - http
